services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Plugin\KomojuPayment43\:
        resource: '../../*'
        exclude: '../../{Entity,Tests,DoctrineMigrations}'

    Plugin\KomojuPayment43\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
